import { bootI18n, bootLocale } from '@/lib/i18n';
import { mount } from '@vue/test-utils';
import { i18nVue, reset, trans } from 'laravel-vue-i18n';
import { afterEach, describe, expect, it } from 'vitest';
import { defineComponent, h } from 'vue';

const LANG = 'fr';
const KEY = 'goals.chart.entry_date';
const VALUE = "Date de l'entrée";

// A resolver standing in for the real glob-backed one. Injecting it keeps the
// assertions independent of the `php_*.json` files, which are generated by the
// Vite plugin and absent under Vitest.
const resolve = () => ({ [KEY]: VALUE });

// Calls `trans()` once, in setup, exactly as the chart components do. This is
// the shape that broke: the value is captured a single time and never
// re-evaluated, so it is only correct if the messages are already loaded.
const SetupTrans = defineComponent({
    setup() {
        const label = trans(KEY);

        return () => h('span', label);
    },
});

const mountWithPlugin = () =>
    mount(SetupTrans, {
        global: { plugins: [[i18nVue, { lang: LANG, resolve }]] },
    });

afterEach(() => {
    reset();
    document.documentElement.removeAttribute('lang');
});

describe('bootLocale', () => {
    it('reads the locale the server rendered onto the html element', () => {
        document.documentElement.setAttribute('lang', 'fr');

        expect(bootLocale()).toBe('fr');
    });

    it('normalises a hyphenated tag to the underscore form', () => {
        document.documentElement.setAttribute('lang', 'pt-BR');

        expect(bootLocale()).toBe('pt_BR');
    });

    it('falls back to en when the html element carries no locale', () => {
        expect(bootLocale()).toBe('en');
    });
});

describe('boot ordering', () => {
    // Documents the broken behaviour. Installing the plugin alone starts an
    // async load that only settles after mount, so a setup-time `trans()` call
    // renders the raw key. If this ever passes, the assertion below stops
    // proving anything.
    it('renders the raw key when the plugin is installed without booting', () => {
        expect(mountWithPlugin().text()).toBe(KEY);
    });

    it('renders the translation when booted before the plugin installs', async () => {
        await bootI18n(LANG, resolve);

        expect(mountWithPlugin().text()).toBe(VALUE);
    });

    it('leaves the language loaded so plugin install applies it synchronously', async () => {
        await bootI18n(LANG, resolve);

        // No await between install and read: this is what mount() does.
        expect(mountWithPlugin().text()).toBe(VALUE);
        expect(trans(KEY)).toBe(VALUE);
    });
});
