import { I18n, loadLanguageAsync } from 'laravel-vue-i18n';

/**
 * Every message file, inlined at build time. `php_*.json` is generated by the
 * `laravel-vue-i18n` Vite plugin from `lang/<locale>/*.php`; `<locale>.json`
 * holds the string-key translations.
 */
const messageFiles = import.meta.glob<{ default: Record<string, string> }>(
    '../../../lang/*.json',
    { eager: true },
);

export type LangResolver = (lang: string) => Record<string, string>;

/**
 * Merge the PHP-derived and JSON message sets for a locale, JSON winning.
 */
export const resolveLang: LangResolver = (lang) => ({
    ...(messageFiles[`../../../lang/php_${lang}.json`]?.default ?? {}),
    ...(messageFiles[`../../../lang/${lang}.json`]?.default ?? {}),
});

/**
 * The locale the server already resolved, read off the `<html lang>` attribute
 * rendered by `app.blade.php`. Available before Inertia boots, unlike the
 * `locale` shared prop.
 */
export const bootLocale = (): string =>
    document.documentElement.lang.replace('-', '_') || 'en';

/**
 * Load the locale's messages before the Vue app mounts.
 *
 * `i18nVue`'s install kicks off an asynchronous load that only settles after
 * mount, so a `trans()` call in `<script setup>` reads an empty message store
 * and captures the raw key forever (template `$t()` escapes this because
 * `activeMessages` is reactive and the render effect re-runs). Warming the
 * shared instance here puts the language in `I18n.loaded`, which makes the
 * later install apply it synchronously.
 *
 * The resolver is synchronous, so this settles in a microtask with no request.
 */
export async function bootI18n(
    lang: string,
    resolve: LangResolver = resolveLang,
): Promise<void> {
    // The published `resolve` type promises a Promise, but the runtime accepts
    // a plain object and takes a synchronous path when given one.
    I18n.getSharedInstance(
        { lang, resolve: resolve as unknown as never },
        true,
    );

    await loadLanguageAsync(lang);
}
